FROM busybox:latest

RUN mkdir -p /tmp/learningBase/train /tmp/learningBase/validation

COPY tmp/learningBase/train/training_data.csv /tmp/learningBase/train/training_data.csv
COPY tmp/learningBase/validation/test_data.csv /tmp/learningBase/validation/test_data.csv

COPY Readme.md /Readme.md
