FROM busybox:latest

RUN mkdir -p /tmp/knowledgeBase

COPY models/customer_churn/ann/currentAiSolution.keras /tmp/knowledgeBase/currentSolution.keras

COPY images/knowledgeBase_customerchurn_ann/README.md /
