FROM busybox:latest

RUN mkdir -p /tmp/activationBase

COPY data/customer-churn-dataset/processed/activation_data.csv /tmp/activationBase/activation_data.csv
COPY images/activationBase_customerchurn/README.md /
