FROM busybox:latest

RUN mkdir -p /tmp/knowledgeBase

COPY models/customer_churn/ols/currentOlsSolution.pkl /tmp/knowledgeBase/currentSolution.pkl

COPY images/knowledgeBase_customerchurn_ols/README.md /
