version: "3.9"

volumes:
  ai_system:
    external: true

services:

  knowledgebase:
    image: beepin6409/knowledgebase_customer_churn_ols
    volumes:
      - ai_system:/tmp

  activationbase:
    image: beepin6409/activationbase_customer_churn
    volumes:
      - ai_system:/tmp

  codebase:
    image: beepin6409/codebase_customer_churn
    volumes:
      - ai_system:/tmp
